services:
  - type: web
    name: astrotalk-server
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    branch: main
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  - type: static
    name: astrotalk-client
    env: static
    buildCommand: "npm install && npm run build"
    startCommand: ""
    plan: free
    branch: main
    region: oregon
    rootDir: frontend
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://astrotalk-server.onrender.com/api"
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
    redirects:
      - source: "/*"
        destination: "/index.html"
        type: 200
